package handler

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"

	"github.com/labstack/echo/v4"
)

const maxProductImageSize = 5 << 20

type UploadHandler struct{ directory string }

func NewUploadHandler(directory string) *UploadHandler { return &UploadHandler{directory: directory} }

// Image accepts safe raster formats only; filenames are generated by the server.
func (h *UploadHandler) Image(c echo.Context) error {
	file, header, err := c.Request().FormFile("file")
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, "select an image file")
	}
	defer file.Close()
	if header.Size <= 0 || header.Size > maxProductImageSize {
		return echo.NewHTTPError(http.StatusRequestEntityTooLarge, "image must be between 1 byte and 5 MB")
	}
	var head [12]byte
	n, err := io.ReadFull(file, head[:])
	if err != nil && err != io.ErrUnexpectedEOF && err != io.EOF {
		return fmt.Errorf("read uploaded image: %w", err)
	}
	extension, contentType := imageType(head[:n])
	if extension == "" {
		return echo.NewHTTPError(http.StatusUnsupportedMediaType, "only JPEG, PNG and WebP images are supported")
	}
	if _, err := file.Seek(0, io.SeekStart); err != nil {
		return fmt.Errorf("rewind uploaded image: %w", err)
	}
	if err := os.MkdirAll(h.directory, 0o755); err != nil {
		return fmt.Errorf("create upload directory: %w", err)
	}
	var token [16]byte
	if _, err := rand.Read(token[:]); err != nil {
		return fmt.Errorf("generate image name: %w", err)
	}
	name := hex.EncodeToString(token[:]) + extension
	path := filepath.Join(h.directory, name)
	dst, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o644)
	if err != nil {
		return fmt.Errorf("create uploaded image: %w", err)
	}
	written, copyErr := io.Copy(dst, io.LimitReader(file, maxProductImageSize+1))
	closeErr := dst.Close()
	if copyErr != nil || closeErr != nil || written > maxProductImageSize {
		_ = os.Remove(path)
		if written > maxProductImageSize {
			return echo.NewHTTPError(http.StatusRequestEntityTooLarge, "image must be no larger than 5 MB")
		}
		if copyErr != nil {
			return fmt.Errorf("save uploaded image: %w", copyErr)
		}
		return fmt.Errorf("close uploaded image: %w", closeErr)
	}
	c.Response().Header().Set("Cache-Control", "public, max-age=31536000, immutable")
	return c.JSON(http.StatusCreated, map[string]string{"url": "/uploads/" + name, "content_type": contentType})
}

func imageType(data []byte) (extension, contentType string) {
	switch {
	case len(data) >= 3 && data[0] == 0xff && data[1] == 0xd8 && data[2] == 0xff:
		return ".jpg", "image/jpeg"
	case len(data) >= 8 && strings.HasPrefix(string(data[:8]), "\x89PNG\r\n\x1a\n"):
		return ".png", "image/png"
	case len(data) >= 12 && string(data[:4]) == "RIFF" && string(data[8:12]) == "WEBP":
		return ".webp", "image/webp"
	default:
		return "", ""
	}
}
